// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7LYj70mjRxvAUOMy7UCXjGKYMTwOpvLc',
    appId: '1:924934731501:web:82696f0875c9d6efdafee4',
    messagingSenderId: '924934731501',
    projectId: 'dronvolador1-b9f04',
    authDomain: 'dronvolador1-b9f04.firebaseapp.com',
    storageBucket: 'dronvolador1-b9f04.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7lJJgVNdt28tnDoblUj7Lniw4QyR0YL0',
    appId: '1:924934731501:android:2c2d79347e7762c1dafee4',
    messagingSenderId: '924934731501',
    projectId: 'dronvolador1-b9f04',
    storageBucket: 'dronvolador1-b9f04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFt6fK1wfW9fY77tvM8fZH1MU4bIKx33c',
    appId: '1:924934731501:ios:68fb9ef38368bba3dafee4',
    messagingSenderId: '924934731501',
    projectId: 'dronvolador1-b9f04',
    storageBucket: 'dronvolador1-b9f04.appspot.com',
    iosBundleId: 'com.example.dronvolador1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFt6fK1wfW9fY77tvM8fZH1MU4bIKx33c',
    appId: '1:924934731501:ios:68fb9ef38368bba3dafee4',
    messagingSenderId: '924934731501',
    projectId: 'dronvolador1-b9f04',
    storageBucket: 'dronvolador1-b9f04.appspot.com',
    iosBundleId: 'com.example.dronvolador1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7LYj70mjRxvAUOMy7UCXjGKYMTwOpvLc',
    appId: '1:924934731501:web:952d66e07428fd32dafee4',
    messagingSenderId: '924934731501',
    projectId: 'dronvolador1-b9f04',
    authDomain: 'dronvolador1-b9f04.firebaseapp.com',
    storageBucket: 'dronvolador1-b9f04.appspot.com',
  );
}
